-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 14:38:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema webclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webclinica
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `webclinica`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`responsavel` (
  `id_responsavel` BINARY(16) NOT NULL,
  `nome_responsavel` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_responsavel`))
;


-- -----------------------------------------------------
-- Table `webclinica`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`paciente` (
  `id_paciente` BINARY(16) NOT NULL,
  `nome_paciente` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `id_responsavel` BINARY(16) NULL,
  PRIMARY KEY (`id_paciente`)
 )
;


-- -----------------------------------------------------
-- Table `webclinica`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`medico` (
  `id_medico` BINARY(16) NOT NULL,
  `nome_medico` VARCHAR(50) NOT NULL,
  `crm` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_medico`))
;


-- -----------------------------------------------------
-- Table `webclinica`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`convenio` (
  `id_convenio` BINARY(16) NOT NULL,
  `nome_convenio` VARCHAR(45) NOT NULL,
  `cod_convenio` VARCHAR(45) NOT NULL,
  `id_medico` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_convenio`) )
;


-- -----------------------------------------------------
-- Table `webclinica`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`consulta` (
  `id_consulta` BINARY(16) NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  `id_medico` BINARY(16) NOT NULL,
  `data_consulta` DATETIME NOT NULL,
  `data_retorno` DATETIME NULL,
  `id_convenio` BINARY(16) NULL,
  PRIMARY KEY (`id_consulta`) )
;


-- -----------------------------------------------------
-- Table `webclinica`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`exame` (
  `id_exame` BINARY(16) NOT NULL,
  `descricao` TEXT NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  `id_consulta` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_exame`) )
;


-- -----------------------------------------------------
-- Table `webclinica`.`diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`diagnostico` (
  `id_diagnostico` BINARY(16) NOT NULL,
  `descricao` TEXT NOT NULL,
  `id_consulta` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_diagnostico`) )
;


-- -----------------------------------------------------
-- Table `webclinica`.`tipo_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`tipo_contato` (
  `codigo_tipo_contato` VARCHAR(1) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_tipo_contato`))
;


-- -----------------------------------------------------
-- Table `webclinica`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`contato` (
  `id_contato` BINARY(16) NOT NULL,
  `contato` VARCHAR(50) NOT NULL,
  `codigo_tipo_contato` VARCHAR(1) NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_contato`) )
;

