-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 14:38:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webclinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webclinica` DEFAULT CHARACTER SET utf8 ;
USE `webclinica` ;

-- -----------------------------------------------------
-- Table `webclinica`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`responsavel` (
  `id_responsavel` BINARY(16) NOT NULL,
  `nome_responsavel` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`paciente` (
  `id_paciente` BINARY(16) NOT NULL,
  `nome_paciente` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `id_responsavel` BINARY(16) NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_id_responsavel_idx` (`id_responsavel` ASC) VISIBLE,
  CONSTRAINT `fk_id_responsavel_764876`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `webclinica`.`responsavel` (`id_responsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`medico` (
  `id_medico` BINARY(16) NOT NULL,
  `nome_medico` VARCHAR(50) NOT NULL,
  `crm` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`convenio` (
  `id_convenio` BINARY(16) NOT NULL,
  `nome_convenio` VARCHAR(45) NOT NULL,
  `cod_convenio` VARCHAR(45) NOT NULL,
  `id_medico` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_convenio`),
  INDEX `fk_id_medico_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_id_medico_65458`
    FOREIGN KEY (`id_medico`)
    REFERENCES `webclinica`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`consulta` (
  `id_consulta` BINARY(16) NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  `id_medico` BINARY(16) NOT NULL,
  `data_consulta` DATETIME NOT NULL,
  `data_retorno` DATETIME NULL,
  `id_convenio` BINARY(16) NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_id_medico_idx` (`id_medico` ASC) VISIBLE,
  INDEX `fk_id_paciente_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_id_convenio_idx` (`id_convenio` ASC) VISIBLE,
  CONSTRAINT `fk_id_medico_984768`
    FOREIGN KEY (`id_medico`)
    REFERENCES `webclinica`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_paciente_876478`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `webclinica`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_convenio_7645467`
    FOREIGN KEY (`id_convenio`)
    REFERENCES `webclinica`.`convenio` (`id_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`exame` (
  `id_exame` BINARY(16) NOT NULL,
  `descricao` TEXT NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  `id_consulta` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_exame`),
  INDEX `fk_id_paciente_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_id_consulta_idx` (`id_consulta` ASC) VISIBLE,
  CONSTRAINT `fk_id_paciente_65467`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `webclinica`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_consulta_765879`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `webclinica`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`diagnostico` (
  `id_diagnostico` BINARY(16) NOT NULL,
  `descricao` TEXT NOT NULL,
  `id_consulta` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_diagnostico`),
  INDEX `fk_id_consulta_idx` (`id_consulta` ASC) VISIBLE,
  CONSTRAINT `fk_id_consulta_4325657`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `webclinica`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`tipo_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`tipo_contato` (
  `codigo_tipo_contato` VARCHAR(1) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_tipo_contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webclinica`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webclinica`.`contato` (
  `id_contato` BINARY(16) NOT NULL,
  `contato` VARCHAR(50) NOT NULL,
  `codigo_tipo_contato` VARCHAR(1) NOT NULL,
  `id_paciente` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_contato`),
  INDEX `fk_id_paciente_9658689_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_tipo_contato_idx` (`codigo_tipo_contato` ASC) VISIBLE,
  CONSTRAINT `fk_id_paciente_9658689`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `webclinica`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_contato`
    FOREIGN KEY (`codigo_tipo_contato`)
    REFERENCES `webclinica`.`tipo_contato` (`codigo_tipo_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
